### ISSUE TITLE
Update `mq_interceptor` to Golang v1.21

### ISSUE THREAD

**Issue by yasinmiran** [ELIXIR-NO/FEGA-Norway#120]
Update the Go version to latest.

**Comment by yasinmiran** [comment]
This has been resolved by PR https://github.com/ELIXIR-NO/FEGA-Norway/pull/115. We updated it to `1.21.8`.

https://github.com/ELIXIR-NO/FEGA-Norway/blob/020aa11c8a476d8172c9cf2933617f2460125b4a/services/mq-interceptor/go.mod#L3

**Comment by joshbaskaran** [comment]
Closing this as it seems to have been resolved.
