### ISSUE TITLE
cega-mock uses unreasonably heavy container.

### ISSUE THREAD

**Issue by joshbaskaran** [ELIXIR-NO/FEGA-Norway#164]
We’re using a Python script (cega-mock.py) to set up a server that responds with the users.json file when we hit the /lega/v1/legas/users/:identifier endpoint. The script is self-contained and only needs the Python runtime that’s bundled with the cegauth image.

**_Expectation_**:
Should be a minimal container instead.

**_Additional info_**:
Probably best to refactor to use Java/Go in the repo instead of python.

**Comment by kjellp** [comment]
Please double check the new expected CEGA endpoint format, the old python code reflects the old format of the endpoint. Updated CEGA_AUTH_URL or similar for live Proxy service connecting to live CEGA Auth service shows the new endpoint format.
