### ISSUE TITLE
Difficult to manage sda-doa

### ISSUE THREAD

**Issue by joshbaskaran** [ELIXIR-NO/FEGA-Norway#181]
Due to the `sda-doa` being part of a different repository, it often requires special attention and doesn't requires extra steps to be tested as part of the main repository.

Suggestion:
Add `sda-doa` as a git submodule to this mono-repo which helps with testing the entire stack while also staying under the Neic-nordic repository.

**Comment by kjellp** [comment]
Reviewed in dev meeting to be closed for now.
